name: textranslator
description: "An application to translate words with Gemini AI API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_tts: ^4.0.2
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - .env